### ISSUE TITLE
Invalid size for routed domains

### ISSUE THREAD

**Issue by vonKrafft** [drwetter/F5-BIGIP-Decoder#1]
Currently, the maximum size of routed domains is set to 2.

*f5_bigip_decoder.sh:169* 
`grep -q -E '^rd[0-9]{1,2}o0{20}f{4}[a-f0-9]{8}o[0-9]{1,5}' <<< "$cookie"`
*f5_bigip_decoder.sh:186* 
`grep -q -E '^rd[0-9]{1,2}o[a-f0-9]{32}o[0-9]{1,5}' <<< "$cookie"`

However, it can happen that this size is greater than 2 (I have seen many times three-digit routed domains). `rd[0-9]{1,2}` should be replaced by `rd[0-9]+` or `rd[^o]+`, assuming the following character is a "o".

```
$ ./f5_bigip_decoder.sh https://xxxxxxxxxxx.fr/

Standard / non-encrypted cookies

   10.215.181.100:80                            | IPv4 pool members in routed domain 338 | BIGipServer~xxxxx=rd338o00000000000000000000ffff0ad7b564o80

A total of 1x non-encrypted cookies found


AES encrypted Cookies

No AES encrypted cookies found


In total:
2 cookies -- 1 F5 BIG IP cookie(s) of which 1 cookie(s) named "BIGipServer~xxxxx"
```

**Comment by drwetter** [comment]
Thx

Why then not ``^rd[0-9]{1,3}``? A regexp should be as strict as possible.

**Comment by vonKrafft** [comment]
I looked for documentation to check if a maximum size was defined for the routed domains, but I did not find this information.

Indeed, it is better to keep a strict regex, but we can not be sure that routed domains with an ID greater than 1000 do not exist. So far, I have not seen one ;)
